/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Relationship = IDL.Variant({
  'other' : IDL.Null,
  'colleague' : IDL.Null,
  'friend' : IDL.Null,
  'family' : IDL.Null,
});
export const Principal = IDL.Principal;
export const ContactId = IDL.Nat;
export const Contact = IDL.Record({
  'id' : ContactId,
  'principal' : IDL.Opt(Principal),
  'relationship' : Relationship,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LocationSnapshot = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'capturedAtNs' : IDL.Int,
  'accuracyM' : IDL.Opt(IDL.Float64),
});
export const ActiveCheckIn = IDL.Record({
  'checkedInAtNs' : IDL.Int,
  'location' : LocationSnapshot,
});
export const CheckInReminderStatus = IDL.Record({
  'lastSentAt' : IDL.Int,
  'intervalSec' : IDL.Nat,
  'enabled' : IDL.Bool,
  'overdueSince' : IDL.Int,
  'overdue' : IDL.Bool,
});
export const CheckInKind = IDL.Variant({
  'checkIn' : IDL.Null,
  'checkOut' : IDL.Null,
});
export const CheckInEvent = IDL.Record({
  'id' : IDL.Nat,
  'kind' : CheckInKind,
  'timestamp' : IDL.Int,
  'location' : LocationSnapshot,
});
export const ChatId = IDL.Nat;
export const ChatType = IDL.Variant({
  'support' : IDL.Null,
  'community' : IDL.Null,
  'direct' : IDL.Null,
});
export const Chat = IDL.Record({
  'id' : ChatId,
  'createdAt' : IDL.Int,
  'participant' : IDL.Opt(IDL.Principal),
  'chatType' : ChatType,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const TimerStatus = IDL.Variant({
  'active' : IDL.Null,
  'stopped' : IDL.Null,
});
export const SafetyTimer = IDL.Record({
  'lastCheckInAtNs' : IDL.Int,
  'status' : TimerStatus,
  'startedAtNs' : IDL.Int,
  'durationSec' : IDL.Nat,
});
export const CheckInReminder = IDL.Record({
  'lastSentAt' : IDL.Int,
  'intervalSec' : IDL.Nat,
  'enabled' : IDL.Bool,
});
export const FakeCall = IDL.Record({
  'startedAt' : IDL.Int,
  'active' : IDL.Bool,
});
export const SosAlertId = IDL.Nat;
export const SosAlertStatus = IDL.Variant({ 'alerted' : IDL.Null });
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const SosAlert = IDL.Record({
  'id' : SosAlertId,
  'status' : SosAlertStatus,
  'alertedContacts' : IDL.Vec(ContactId),
  'timestamp' : IDL.Int,
  'location' : Location,
});
export const MessageId = IDL.Nat;
export const MessageKind = IDL.Variant({
  'text' : IDL.Null,
  'image' : IDL.Null,
  'location' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'kind' : MessageKind,
  'text' : IDL.Opt(IDL.Text),
  'sender' : IDL.Principal,
  'imageUrl' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'location' : IDL.Opt(Location),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addContact' : IDL.Func(
      [IDL.Text, IDL.Text, Relationship, IDL.Opt(Principal)],
      [Contact],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([LocationSnapshot], [ActiveCheckIn], []),
  'checkInReminderStatus' : IDL.Func(
      [],
      [IDL.Opt(CheckInReminderStatus)],
      ['query'],
    ),
  'checkOut' : IDL.Func([LocationSnapshot], [IDL.Opt(CheckInEvent)], []),
  'createDirectChat' : IDL.Func([Principal], [Chat], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'extendTimer' : IDL.Func([IDL.Nat], [SafetyTimer], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChat' : IDL.Func([ChatId], [IDL.Opt(Chat)], ['query']),
  'getCheckInHistoryFor' : IDL.Func(
      [Principal],
      [IDL.Vec(CheckInEvent)],
      ['query'],
    ),
  'getCheckInReminder' : IDL.Func([], [IDL.Opt(CheckInReminder)], ['query']),
  'getCheckInState' : IDL.Func([], [IDL.Opt(ActiveCheckIn)], ['query']),
  'getCommunityChat' : IDL.Func([], [Chat], []),
  'getDiscreetMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getFakeCall' : IDL.Func([], [IDL.Opt(FakeCall)], ['query']),
  'getLocation' : IDL.Func([], [IDL.Opt(LocationSnapshot)], ['query']),
  'getSosAlert' : IDL.Func([SosAlertId], [IDL.Opt(SosAlert)], ['query']),
  'getSupportChat' : IDL.Func([], [Chat], []),
  'getTimer' : IDL.Func([], [IDL.Opt(SafetyTimer)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
  'listCheckInHistory' : IDL.Func([], [IDL.Vec(CheckInEvent)], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'listMessages' : IDL.Func([ChatId], [IDL.Vec(ChatMessage)], ['query']),
  'listSosAlerts' : IDL.Func([], [IDL.Vec(SosAlert)], ['query']),
  'markCheckIn' : IDL.Func([], [IDL.Opt(CheckInReminder)], []),
  'removeContact' : IDL.Func([ContactId], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func(
      [ChatId, MessageKind, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ChatMessage],
      [],
    ),
  'setCheckInReminder' : IDL.Func([IDL.Nat], [CheckInReminder], []),
  'setDiscreetMode' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'shareLocation' : IDL.Func([ChatId, Location], [ChatMessage], []),
  'startFakeCall' : IDL.Func([], [FakeCall], []),
  'startTimer' : IDL.Func([IDL.Nat], [SafetyTimer], []),
  'stopFakeCall' : IDL.Func([], [IDL.Opt(FakeCall)], []),
  'stopTimer' : IDL.Func([], [IDL.Opt(SafetyTimer)], []),
  'timerCheckIn' : IDL.Func([LocationSnapshot], [SafetyTimer], []),
  'triggerSos' : IDL.Func([Location], [SosAlert], []),
  'updateContact' : IDL.Func(
      [ContactId, IDL.Text, IDL.Text, Relationship, IDL.Opt(Principal)],
      [IDL.Opt(Contact)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Relationship = IDL.Variant({
    'other' : IDL.Null,
    'colleague' : IDL.Null,
    'friend' : IDL.Null,
    'family' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const ContactId = IDL.Nat;
  const Contact = IDL.Record({
    'id' : ContactId,
    'principal' : IDL.Opt(Principal),
    'relationship' : Relationship,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LocationSnapshot = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'capturedAtNs' : IDL.Int,
    'accuracyM' : IDL.Opt(IDL.Float64),
  });
  const ActiveCheckIn = IDL.Record({
    'checkedInAtNs' : IDL.Int,
    'location' : LocationSnapshot,
  });
  const CheckInReminderStatus = IDL.Record({
    'lastSentAt' : IDL.Int,
    'intervalSec' : IDL.Nat,
    'enabled' : IDL.Bool,
    'overdueSince' : IDL.Int,
    'overdue' : IDL.Bool,
  });
  const CheckInKind = IDL.Variant({
    'checkIn' : IDL.Null,
    'checkOut' : IDL.Null,
  });
  const CheckInEvent = IDL.Record({
    'id' : IDL.Nat,
    'kind' : CheckInKind,
    'timestamp' : IDL.Int,
    'location' : LocationSnapshot,
  });
  const ChatId = IDL.Nat;
  const ChatType = IDL.Variant({
    'support' : IDL.Null,
    'community' : IDL.Null,
    'direct' : IDL.Null,
  });
  const Chat = IDL.Record({
    'id' : ChatId,
    'createdAt' : IDL.Int,
    'participant' : IDL.Opt(IDL.Principal),
    'chatType' : ChatType,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const TimerStatus = IDL.Variant({
    'active' : IDL.Null,
    'stopped' : IDL.Null,
  });
  const SafetyTimer = IDL.Record({
    'lastCheckInAtNs' : IDL.Int,
    'status' : TimerStatus,
    'startedAtNs' : IDL.Int,
    'durationSec' : IDL.Nat,
  });
  const CheckInReminder = IDL.Record({
    'lastSentAt' : IDL.Int,
    'intervalSec' : IDL.Nat,
    'enabled' : IDL.Bool,
  });
  const FakeCall = IDL.Record({ 'startedAt' : IDL.Int, 'active' : IDL.Bool });
  const SosAlertId = IDL.Nat;
  const SosAlertStatus = IDL.Variant({ 'alerted' : IDL.Null });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const SosAlert = IDL.Record({
    'id' : SosAlertId,
    'status' : SosAlertStatus,
    'alertedContacts' : IDL.Vec(ContactId),
    'timestamp' : IDL.Int,
    'location' : Location,
  });
  const MessageId = IDL.Nat;
  const MessageKind = IDL.Variant({
    'text' : IDL.Null,
    'image' : IDL.Null,
    'location' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'kind' : MessageKind,
    'text' : IDL.Opt(IDL.Text),
    'sender' : IDL.Principal,
    'imageUrl' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'location' : IDL.Opt(Location),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addContact' : IDL.Func(
        [IDL.Text, IDL.Text, Relationship, IDL.Opt(Principal)],
        [Contact],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([LocationSnapshot], [ActiveCheckIn], []),
    'checkInReminderStatus' : IDL.Func(
        [],
        [IDL.Opt(CheckInReminderStatus)],
        ['query'],
      ),
    'checkOut' : IDL.Func([LocationSnapshot], [IDL.Opt(CheckInEvent)], []),
    'createDirectChat' : IDL.Func([Principal], [Chat], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'extendTimer' : IDL.Func([IDL.Nat], [SafetyTimer], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChat' : IDL.Func([ChatId], [IDL.Opt(Chat)], ['query']),
    'getCheckInHistoryFor' : IDL.Func(
        [Principal],
        [IDL.Vec(CheckInEvent)],
        ['query'],
      ),
    'getCheckInReminder' : IDL.Func([], [IDL.Opt(CheckInReminder)], ['query']),
    'getCheckInState' : IDL.Func([], [IDL.Opt(ActiveCheckIn)], ['query']),
    'getCommunityChat' : IDL.Func([], [Chat], []),
    'getDiscreetMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getFakeCall' : IDL.Func([], [IDL.Opt(FakeCall)], ['query']),
    'getLocation' : IDL.Func([], [IDL.Opt(LocationSnapshot)], ['query']),
    'getSosAlert' : IDL.Func([SosAlertId], [IDL.Opt(SosAlert)], ['query']),
    'getSupportChat' : IDL.Func([], [Chat], []),
    'getTimer' : IDL.Func([], [IDL.Opt(SafetyTimer)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
    'listCheckInHistory' : IDL.Func([], [IDL.Vec(CheckInEvent)], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'listMessages' : IDL.Func([ChatId], [IDL.Vec(ChatMessage)], ['query']),
    'listSosAlerts' : IDL.Func([], [IDL.Vec(SosAlert)], ['query']),
    'markCheckIn' : IDL.Func([], [IDL.Opt(CheckInReminder)], []),
    'removeContact' : IDL.Func([ContactId], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func(
        [ChatId, MessageKind, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ChatMessage],
        [],
      ),
    'setCheckInReminder' : IDL.Func([IDL.Nat], [CheckInReminder], []),
    'setDiscreetMode' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'shareLocation' : IDL.Func([ChatId, Location], [ChatMessage], []),
    'startFakeCall' : IDL.Func([], [FakeCall], []),
    'startTimer' : IDL.Func([IDL.Nat], [SafetyTimer], []),
    'stopFakeCall' : IDL.Func([], [IDL.Opt(FakeCall)], []),
    'stopTimer' : IDL.Func([], [IDL.Opt(SafetyTimer)], []),
    'timerCheckIn' : IDL.Func([LocationSnapshot], [SafetyTimer], []),
    'triggerSos' : IDL.Func([Location], [SosAlert], []),
    'updateContact' : IDL.Func(
        [ContactId, IDL.Text, IDL.Text, Relationship, IDL.Opt(Principal)],
        [IDL.Opt(Contact)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };