/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveCheckIn {
  'checkedInAtNs' : bigint,
  'location' : LocationSnapshot,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Chat {
  'id' : ChatId,
  'createdAt' : bigint,
  'participant' : [] | [Principal],
  'chatType' : ChatType,
}
export type ChatId = bigint;
export interface ChatMessage {
  'id' : MessageId,
  'kind' : MessageKind,
  'text' : [] | [string],
  'sender' : Principal,
  'imageUrl' : [] | [string],
  'timestamp' : bigint,
  'location' : [] | [Location],
}
export type ChatType = { 'support' : null } |
  { 'community' : null } |
  { 'direct' : null };
export interface CheckInEvent {
  'id' : bigint,
  'kind' : CheckInKind,
  'timestamp' : bigint,
  'location' : LocationSnapshot,
}
export type CheckInKind = { 'checkIn' : null } |
  { 'checkOut' : null };
export interface CheckInReminder {
  'lastSentAt' : bigint,
  'intervalSec' : bigint,
  'enabled' : boolean,
}
export interface CheckInReminderStatus {
  'lastSentAt' : bigint,
  'intervalSec' : bigint,
  'enabled' : boolean,
  'overdueSince' : bigint,
  'overdue' : boolean,
}
export interface Contact {
  'id' : ContactId,
  'principal' : [] | [Principal],
  'relationship' : Relationship,
  'name' : string,
  'phone' : string,
}
export type ContactId = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FakeCall { 'startedAt' : bigint, 'active' : boolean }
export interface Location { 'latitude' : number, 'longitude' : number }
export interface LocationSnapshot {
  'latitude' : number,
  'longitude' : number,
  'capturedAtNs' : bigint,
  'accuracyM' : [] | [number],
}
export type MessageId = bigint;
export type MessageKind = { 'text' : null } |
  { 'image' : null } |
  { 'location' : null };
export type Principal = Principal;
export type Relationship = { 'other' : null } |
  { 'colleague' : null } |
  { 'friend' : null } |
  { 'family' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SafetyTimer {
  'lastCheckInAtNs' : bigint,
  'status' : TimerStatus,
  'startedAtNs' : bigint,
  'durationSec' : bigint,
}
export interface SosAlert {
  'id' : SosAlertId,
  'status' : SosAlertStatus,
  'alertedContacts' : Array<ContactId>,
  'timestamp' : bigint,
  'location' : Location,
}
export type SosAlertId = bigint;
export type SosAlertStatus = { 'alerted' : null };
export type TimerStatus = { 'active' : null } |
  { 'stopped' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addContact' : ActorMethod<
    [string, string, Relationship, [] | [Principal]],
    Contact
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[LocationSnapshot], ActiveCheckIn>,
  'checkInReminderStatus' : ActorMethod<[], [] | [CheckInReminderStatus]>,
  'checkOut' : ActorMethod<[LocationSnapshot], [] | [CheckInEvent]>,
  'createDirectChat' : ActorMethod<[Principal], Chat>,
  'execute' : ActorMethod<[string], Result>,
  'extendTimer' : ActorMethod<[bigint], SafetyTimer>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChat' : ActorMethod<[ChatId], [] | [Chat]>,
  'getCheckInHistoryFor' : ActorMethod<[Principal], Array<CheckInEvent>>,
  'getCheckInReminder' : ActorMethod<[], [] | [CheckInReminder]>,
  'getCheckInState' : ActorMethod<[], [] | [ActiveCheckIn]>,
  'getCommunityChat' : ActorMethod<[], Chat>,
  'getDiscreetMode' : ActorMethod<[], boolean>,
  'getFakeCall' : ActorMethod<[], [] | [FakeCall]>,
  'getLocation' : ActorMethod<[], [] | [LocationSnapshot]>,
  'getSosAlert' : ActorMethod<[SosAlertId], [] | [SosAlert]>,
  'getSupportChat' : ActorMethod<[], Chat>,
  'getTimer' : ActorMethod<[], [] | [SafetyTimer]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChats' : ActorMethod<[], Array<Chat>>,
  'listCheckInHistory' : ActorMethod<[], Array<CheckInEvent>>,
  'listContacts' : ActorMethod<[], Array<Contact>>,
  'listMessages' : ActorMethod<[ChatId], Array<ChatMessage>>,
  'listSosAlerts' : ActorMethod<[], Array<SosAlert>>,
  'markCheckIn' : ActorMethod<[], [] | [CheckInReminder]>,
  'removeContact' : ActorMethod<[ContactId], boolean>,
  'schema' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<
    [ChatId, MessageKind, [] | [string], [] | [string]],
    ChatMessage
  >,
  'setCheckInReminder' : ActorMethod<[bigint], CheckInReminder>,
  'setDiscreetMode' : ActorMethod<[boolean], boolean>,
  'shareLocation' : ActorMethod<[ChatId, Location], ChatMessage>,
  'startFakeCall' : ActorMethod<[], FakeCall>,
  'startTimer' : ActorMethod<[bigint], SafetyTimer>,
  'stopFakeCall' : ActorMethod<[], [] | [FakeCall]>,
  'stopTimer' : ActorMethod<[], [] | [SafetyTimer]>,
  'timerCheckIn' : ActorMethod<[LocationSnapshot], SafetyTimer>,
  'triggerSos' : ActorMethod<[Location], SosAlert>,
  'updateContact' : ActorMethod<
    [ContactId, string, string, Relationship, [] | [Principal]],
    [] | [Contact]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];