/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Location {
    latitude: number;
    longitude: number;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ActiveCheckIn {
    checkedInAtNs: bigint;
    location: LocationSnapshot;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ChatMessage {
    id: MessageId;
    kind: MessageKind;
    text?: string;
    sender: Principal;
    imageUrl?: string;
    timestamp: bigint;
    location?: Location;
}
export interface SafetyTimer {
    lastCheckInAtNs: bigint;
    status: TimerStatus;
    startedAtNs: bigint;
    durationSec: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface LocationSnapshot {
    latitude: number;
    longitude: number;
    capturedAtNs: bigint;
    accuracyM?: number;
}
export type SosAlertId = bigint;
export interface SosAlert {
    id: SosAlertId;
    status: SosAlertStatus;
    alertedContacts: Array<ContactId>;
    timestamp: bigint;
    location: Location;
}
export interface FakeCall {
    startedAt: bigint;
    active: boolean;
}
export interface CheckInReminder {
    lastSentAt: bigint;
    intervalSec: bigint;
    enabled: boolean;
}
export type ChatId = bigint;
export interface Contact {
    id: ContactId;
    principal?: Principal;
    relationship: Relationship;
    name: string;
    phone: string;
}
export interface CheckInReminderStatus {
    lastSentAt: bigint;
    intervalSec: bigint;
    enabled: boolean;
    overdueSince: bigint;
    overdue: boolean;
}
export type Principal = Principal;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface CheckInEvent {
    id: bigint;
    kind: CheckInKind;
    timestamp: bigint;
    location: LocationSnapshot;
}
export type MessageId = bigint;
export interface Chat {
    id: ChatId;
    createdAt: bigint;
    participant?: Principal;
    chatType: ChatType;
}
export type ContactId = bigint;
export enum ChatType {
    support = "support",
    community = "community",
    direct = "direct"
}
export enum CheckInKind {
    checkIn = "checkIn",
    checkOut = "checkOut"
}
export enum MessageKind {
    text = "text",
    image = "image",
    location = "location"
}
export enum Relationship {
    other = "other",
    colleague = "colleague",
    friend = "friend",
    family = "family"
}
export enum SosAlertStatus {
    alerted = "alerted"
}
export enum TimerStatus {
    active = "active",
    stopped = "stopped"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addContact(name: string, phone: string, relationship: Relationship, principal: Principal | null): Promise<Contact>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkIn(location: LocationSnapshot): Promise<ActiveCheckIn>;
    checkInReminderStatus(): Promise<CheckInReminderStatus | null>;
    checkOut(location: LocationSnapshot): Promise<CheckInEvent | null>;
    createDirectChat(participant: Principal): Promise<Chat>;
    execute(qJson: string): Promise<Result>;
    extendTimer(extraSec: bigint): Promise<SafetyTimer>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getChat(chatId: ChatId): Promise<Chat | null>;
    getCheckInHistoryFor(user: Principal): Promise<Array<CheckInEvent>>;
    getCheckInReminder(): Promise<CheckInReminder | null>;
    getCheckInState(): Promise<ActiveCheckIn | null>;
    getCommunityChat(): Promise<Chat>;
    getDiscreetMode(): Promise<boolean>;
    getFakeCall(): Promise<FakeCall | null>;
    getLocation(): Promise<LocationSnapshot | null>;
    getSosAlert(id: SosAlertId): Promise<SosAlert | null>;
    getSupportChat(): Promise<Chat>;
    getTimer(): Promise<SafetyTimer | null>;
    isCallerAdmin(): Promise<boolean>;
    listChats(): Promise<Array<Chat>>;
    listCheckInHistory(): Promise<Array<CheckInEvent>>;
    listContacts(): Promise<Array<Contact>>;
    listMessages(chatId: ChatId): Promise<Array<ChatMessage>>;
    listSosAlerts(): Promise<Array<SosAlert>>;
    markCheckIn(): Promise<CheckInReminder | null>;
    removeContact(id: ContactId): Promise<boolean>;
    schema(): Promise<string>;
    sendMessage(chatId: ChatId, kind: MessageKind, text: string | null, imageUrl: string | null): Promise<ChatMessage>;
    setCheckInReminder(intervalSec: bigint): Promise<CheckInReminder>;
    setDiscreetMode(enabled: boolean): Promise<boolean>;
    shareLocation(chatId: ChatId, location: Location): Promise<ChatMessage>;
    startFakeCall(): Promise<FakeCall>;
    startTimer(durationSec: bigint): Promise<SafetyTimer>;
    stopFakeCall(): Promise<FakeCall | null>;
    stopTimer(): Promise<SafetyTimer | null>;
    timerCheckIn(location: LocationSnapshot): Promise<SafetyTimer>;
    triggerSos(location: Location): Promise<SosAlert>;
    updateContact(id: ContactId, name: string, phone: string, relationship: Relationship, principal: Principal | null): Promise<Contact | null>;
}
import type { ActiveCheckIn as _ActiveCheckIn, Cell as _Cell, Chat as _Chat, ChatId as _ChatId, ChatMessage as _ChatMessage, ChatType as _ChatType, CheckInEvent as _CheckInEvent, CheckInKind as _CheckInKind, CheckInReminder as _CheckInReminder, CheckInReminderStatus as _CheckInReminderStatus, Contact as _Contact, ContactId as _ContactId, Error as _Error, FakeCall as _FakeCall, Location as _Location, LocationSnapshot as _LocationSnapshot, MessageId as _MessageId, MessageKind as _MessageKind, Principal as _Principal, Relationship as _Relationship, Result as _Result, Result__1 as _Result__1, SafetyTimer as _SafetyTimer, SosAlert as _SosAlert, SosAlertId as _SosAlertId, SosAlertStatus as _SosAlertStatus, TimerStatus as _TimerStatus, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addContact(arg0: string, arg1: string, arg2: Relationship, arg3: Principal | null): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1, to_candid_Relationship_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Contact_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1, to_candid_Relationship_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Contact_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkIn(arg0: LocationSnapshot): Promise<ActiveCheckIn> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(to_candid_LocationSnapshot_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ActiveCheckIn_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(to_candid_LocationSnapshot_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ActiveCheckIn_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkInReminderStatus(): Promise<CheckInReminderStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInReminderStatus();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInReminderStatus();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkOut(arg0: LocationSnapshot): Promise<CheckInEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOut(to_candid_LocationSnapshot_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOut(to_candid_LocationSnapshot_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDirectChat(arg0: Principal): Promise<Chat> {
        if (this.processError) {
            try {
                const result = await this.actor.createDirectChat(arg0);
                return from_candid_Chat_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDirectChat(arg0);
            return from_candid_Chat_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async extendTimer(arg0: bigint): Promise<SafetyTimer> {
        if (this.processError) {
            try {
                const result = await this.actor.extendTimer(arg0);
                return from_candid_SafetyTimer_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extendTimer(arg0);
            return from_candid_SafetyTimer_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChat(arg0: ChatId): Promise<Chat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChat(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChat(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInHistoryFor(arg0: Principal): Promise<Array<CheckInEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInHistoryFor(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInHistoryFor(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInReminder(): Promise<CheckInReminder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInReminder();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInReminder();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckInState(): Promise<ActiveCheckIn | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInState();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInState();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityChat(): Promise<Chat> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityChat();
                return from_candid_Chat_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityChat();
            return from_candid_Chat_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiscreetMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscreetMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscreetMode();
            return result;
        }
    }
    async getFakeCall(): Promise<FakeCall | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFakeCall();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFakeCall();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(): Promise<LocationSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSosAlert(arg0: SosAlertId): Promise<SosAlert | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSosAlert(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSosAlert(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupportChat(): Promise<Chat> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportChat();
                return from_candid_Chat_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportChat();
            return from_candid_Chat_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimer(): Promise<SafetyTimer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimer();
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimer();
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listChats(): Promise<Array<Chat>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChats();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChats();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCheckInHistory(): Promise<Array<CheckInEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCheckInHistory();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCheckInHistory();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContacts();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContacts();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessages(arg0: ChatId): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessages(arg0);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessages(arg0);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSosAlerts(): Promise<Array<SosAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSosAlerts();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSosAlerts();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async markCheckIn(): Promise<CheckInReminder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markCheckIn();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCheckIn();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeContact(arg0: ContactId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeContact(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async sendMessage(arg0: ChatId, arg1: MessageKind, arg2: string | null, arg3: string | null): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, to_candid_MessageKind_n69(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg3));
                return from_candid_ChatMessage_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, to_candid_MessageKind_n69(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n71(this._uploadFile, this._downloadFile, arg3));
            return from_candid_ChatMessage_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async setCheckInReminder(arg0: bigint): Promise<CheckInReminder> {
        if (this.processError) {
            try {
                const result = await this.actor.setCheckInReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCheckInReminder(arg0);
            return result;
        }
    }
    async setDiscreetMode(arg0: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDiscreetMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDiscreetMode(arg0);
            return result;
        }
    }
    async shareLocation(arg0: ChatId, arg1: Location): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.shareLocation(arg0, arg1);
                return from_candid_ChatMessage_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareLocation(arg0, arg1);
            return from_candid_ChatMessage_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async startFakeCall(): Promise<FakeCall> {
        if (this.processError) {
            try {
                const result = await this.actor.startFakeCall();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startFakeCall();
            return result;
        }
    }
    async startTimer(arg0: bigint): Promise<SafetyTimer> {
        if (this.processError) {
            try {
                const result = await this.actor.startTimer(arg0);
                return from_candid_SafetyTimer_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTimer(arg0);
            return from_candid_SafetyTimer_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async stopFakeCall(): Promise<FakeCall | null> {
        if (this.processError) {
            try {
                const result = await this.actor.stopFakeCall();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopFakeCall();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async stopTimer(): Promise<SafetyTimer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.stopTimer();
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopTimer();
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async timerCheckIn(arg0: LocationSnapshot): Promise<SafetyTimer> {
        if (this.processError) {
            try {
                const result = await this.actor.timerCheckIn(to_candid_LocationSnapshot_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SafetyTimer_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.timerCheckIn(to_candid_LocationSnapshot_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SafetyTimer_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async triggerSos(arg0: Location): Promise<SosAlert> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerSos(arg0);
                return from_candid_SosAlert_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerSos(arg0);
            return from_candid_SosAlert_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContact(arg0: ContactId, arg1: string, arg2: string, arg3: Relationship, arg4: Principal | null): Promise<Contact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1, arg2, to_candid_Relationship_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
                return from_candid_opt_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1, arg2, to_candid_Relationship_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
            return from_candid_opt_n72(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActiveCheckIn_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActiveCheckIn): ActiveCheckIn {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_ChatType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatType): ChatType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Chat_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chat): Chat {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_CheckInEvent_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckInEvent): CheckInEvent {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CheckInKind_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckInKind): CheckInKind {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Contact_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contact): Contact {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_LocationSnapshot_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationSnapshot): LocationSnapshot {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_MessageKind_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageKind): MessageKind {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Relationship_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Relationship): Relationship {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_SafetyTimer_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SafetyTimer): SafetyTimer {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_SosAlertStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SosAlertStatus): SosAlertStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_SosAlert_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SosAlert): SosAlert {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_TimerStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimerStatus): TimerStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CheckInReminderStatus]): CheckInReminderStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CheckInEvent]): CheckInEvent | null {
    return value.length === 0 ? null : from_candid_CheckInEvent_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chat]): Chat | null {
    return value.length === 0 ? null : from_candid_Chat_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CheckInReminder]): CheckInReminder | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActiveCheckIn]): ActiveCheckIn | null {
    return value.length === 0 ? null : from_candid_ActiveCheckIn_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FakeCall]): FakeCall | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocationSnapshot]): LocationSnapshot | null {
    return value.length === 0 ? null : from_candid_LocationSnapshot_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SosAlert]): SosAlert | null {
    return value.length === 0 ? null : from_candid_SosAlert_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SafetyTimer]): SafetyTimer | null {
    return value.length === 0 ? null : from_candid_SafetyTimer_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contact]): Contact | null {
    return value.length === 0 ? null : from_candid_Contact_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkedInAtNs: bigint;
    location: _LocationSnapshot;
}): {
    checkedInAtNs: bigint;
    location: LocationSnapshot;
} {
    return {
        checkedInAtNs: value.checkedInAtNs,
        location: from_candid_LocationSnapshot_n19(_uploadFile, _downloadFile, value.location)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    longitude: number;
    capturedAtNs: bigint;
    accuracyM: [] | [number];
}): {
    latitude: number;
    longitude: number;
    capturedAtNs: bigint;
    accuracyM?: number;
} {
    return {
        latitude: value.latitude,
        longitude: value.longitude,
        capturedAtNs: value.capturedAtNs,
        accuracyM: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.accuracyM))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _CheckInKind;
    timestamp: bigint;
    location: _LocationSnapshot;
}): {
    id: bigint;
    kind: CheckInKind;
    timestamp: bigint;
    location: LocationSnapshot;
} {
    return {
        id: value.id,
        kind: from_candid_CheckInKind_n26(_uploadFile, _downloadFile, value.kind),
        timestamp: value.timestamp,
        location: from_candid_LocationSnapshot_n19(_uploadFile, _downloadFile, value.location)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChatId;
    createdAt: bigint;
    participant: [] | [Principal];
    chatType: _ChatType;
}): {
    id: ChatId;
    createdAt: bigint;
    participant?: Principal;
    chatType: ChatType;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        participant: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.participant)),
        chatType: from_candid_ChatType_n31(_uploadFile, _downloadFile, value.chatType)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n35(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n39(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastCheckInAtNs: bigint;
    status: _TimerStatus;
    startedAtNs: bigint;
    durationSec: bigint;
}): {
    lastCheckInAtNs: bigint;
    status: TimerStatus;
    startedAtNs: bigint;
    durationSec: bigint;
} {
    return {
        lastCheckInAtNs: value.lastCheckInAtNs,
        status: from_candid_TimerStatus_n43(_uploadFile, _downloadFile, value.status),
        startedAtNs: value.startedAtNs,
        durationSec: value.durationSec
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SosAlertId;
    status: _SosAlertStatus;
    alertedContacts: Array<_ContactId>;
    timestamp: bigint;
    location: _Location;
}): {
    id: SosAlertId;
    status: SosAlertStatus;
    alertedContacts: Array<ContactId>;
    timestamp: bigint;
    location: Location;
} {
    return {
        id: value.id,
        status: from_candid_SosAlertStatus_n56(_uploadFile, _downloadFile, value.status),
        alertedContacts: value.alertedContacts,
        timestamp: value.timestamp,
        location: value.location
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    kind: _MessageKind;
    text: [] | [string];
    sender: Principal;
    imageUrl: [] | [string];
    timestamp: bigint;
    location: [] | [_Location];
}): {
    id: MessageId;
    kind: MessageKind;
    text?: string;
    sender: Principal;
    imageUrl?: string;
    timestamp: bigint;
    location?: Location;
} {
    return {
        id: value.id,
        kind: from_candid_MessageKind_n64(_uploadFile, _downloadFile, value.kind),
        text: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.text)),
        sender: value.sender,
        imageUrl: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.imageUrl)),
        timestamp: value.timestamp,
        location: record_opt_to_undefined(from_candid_opt_n67(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ContactId;
    principal: [] | [_Principal];
    relationship: _Relationship;
    name: string;
    phone: string;
}): {
    id: ContactId;
    principal?: Principal;
    relationship: Relationship;
    name: string;
    phone: string;
} {
    return {
        id: value.id,
        principal: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.principal)),
        relationship: from_candid_Relationship_n11(_uploadFile, _downloadFile, value.relationship),
        name: value.name,
        phone: value.phone
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    colleague: null;
} | {
    friend: null;
} | {
    family: null;
}): Relationship {
    return "other" in value ? Relationship.other : "colleague" in value ? Relationship.colleague : "friend" in value ? Relationship.friend : "family" in value ? Relationship.family : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkIn: null;
} | {
    checkOut: null;
}): CheckInKind {
    return "checkIn" in value ? CheckInKind.checkIn : "checkOut" in value ? CheckInKind.checkOut : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    support: null;
} | {
    community: null;
} | {
    direct: null;
}): ChatType {
    return "support" in value ? ChatType.support : "community" in value ? ChatType.community : "direct" in value ? ChatType.direct : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    stopped: null;
}): TimerStatus {
    return "active" in value ? TimerStatus.active : "stopped" in value ? TimerStatus.stopped : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alerted: null;
}): SosAlertStatus {
    return "alerted" in value ? SosAlertStatus.alerted : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    image: null;
} | {
    location: null;
}): MessageKind {
    return "text" in value ? MessageKind.text : "image" in value ? MessageKind.image : "location" in value ? MessageKind.location : value;
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CheckInEvent>): Array<CheckInEvent> {
    return value.map((x)=>from_candid_CheckInEvent_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chat>): Array<Chat> {
    return value.map((x)=>from_candid_Chat_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contact>): Array<Contact> {
    return value.map((x)=>from_candid_Contact_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n62(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SosAlert>): Array<SosAlert> {
    return value.map((x)=>from_candid_SosAlert_n54(_uploadFile, _downloadFile, x));
}
function to_candid_LocationSnapshot_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationSnapshot): _LocationSnapshot {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_MessageKind_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageKind): _MessageKind {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_Relationship_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Relationship): _Relationship {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [_Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    longitude: number;
    capturedAtNs: bigint;
    accuracyM?: number;
}): {
    latitude: number;
    longitude: number;
    capturedAtNs: bigint;
    accuracyM: [] | [number];
} {
    return {
        latitude: value.latitude,
        longitude: value.longitude,
        capturedAtNs: value.capturedAtNs,
        accuracyM: value.accuracyM ? candid_some(value.accuracyM) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Relationship): {
    other: null;
} | {
    colleague: null;
} | {
    friend: null;
} | {
    family: null;
} {
    return value == Relationship.other ? {
        other: null
    } : value == Relationship.colleague ? {
        colleague: null
    } : value == Relationship.friend ? {
        friend: null
    } : value == Relationship.family ? {
        family: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageKind): {
    text: null;
} | {
    image: null;
} | {
    location: null;
} {
    return value == MessageKind.text ? {
        text: null
    } : value == MessageKind.image ? {
        image: null
    } : value == MessageKind.location ? {
        location: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
